package com.aditya.aiassistant.model

sealed class Command {
    data class CallContact(val name: String) : Command()
    data class SendSms(val name: String, val message: String) : Command()
    data class OpenApp(val appName: String) : Command()
    data class SetAlarm(val hour: Int, val minute: Int) : Command()
    data class SetTimer(val minutes: Int) : Command()
    data class SearchWeb(val query: String) : Command()
    data class AiChat(val message: String) : Command()
    data object ToggleFlashlight : Command()
    data object ToggleWifi : Command()
    data object ToggleBluetooth : Command()
    data object TakeScreenshot : Command()
    data object IncreaseVolume : Command()
    data object DecreaseVolume : Command()
    data object MuteVolume : Command()
    data object ReadNotifications : Command()
    data object WhatTime : Command()
    data object WhatDate : Command()
    data object BatteryLevel : Command()
    data object PickCall : Command()
    data object RejectCall : Command()
    data object PlayMusic : Command()
    data object PauseMusic : Command()
    data object NextTrack : Command()
    data object PreviousTrack : Command()
    data object TakePhoto : Command()
    data object OpenCamera : Command()
    data object Greet : Command()
    data object Unknown : Command()
}
